
INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-4,"Cream Cheese",1,5);
INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-6,"Ervas Finas",2,6);
INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-5,"Molho agridoce",3,6);

INSERT INTO PRODUTO(DESCPROD,VLRPROD,QTDPROD) VALUES ("Refrigerante Lata",5.50,20);
INSERT INTO PRODUTO(DESCPROD,VLRPROD,QTDPROD) VALUES ("X-Moda da casa",8.50,20);


INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-1,'Sanduiche Árabe',17.90,6);
INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-2,"Sanduiche Vegetariano",15.99,8);
INSERT INTO PRODUTO(CODPROD,DESCPROD,VLRPROD,QTDPROD) VALUES (-3,"X-Tudo",15.99,8);